name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      MAIN_CMD_NAME: memory
      ITEM_CMD_NAME: _memory-item
      HAXE_VERSION: latest
      NODE_VERSION: 16

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install lix, haxe ${{ env.HAXE_VERSION }} and dependencies
      run: |
            npm i -g lix
            lix install haxe ${{ env.HAXE_VERSION }}
            lix download

    - name: Compile main project
      run: haxe deploy.hxml

    - name: Package main to release
      run: |
        mkdir ${{ env.MAIN_CMD_NAME }}
        mv index.js ${{ env.MAIN_CMD_NAME }}
        mv presets.json ${{ env.MAIN_CMD_NAME }}
        mv readme.md ${{ env.MAIN_CMD_NAME }}
        echo '{"repository": "http://github.com/${{ github.repository }}","filename": "${{ env.MAIN_CMD_NAME }}.zip","version": "${{ github.ref_name }}"}' > ${{ env.MAIN_CMD_NAME }}/.info
        zip -r ${{ env.MAIN_CMD_NAME }} ${{ env.MAIN_CMD_NAME }}

    - name: Compile item project
      run: haxe deploy_item.hxml

    - name: Package item to release
      run: |
        mkdir ${{ env.ITEM_CMD_NAME }}
        mv item/index.js ${{ env.ITEM_CMD_NAME }}
        echo '{"repository": "http://github.com/${{ github.repository }}","filename": "${{ env.ITEM_CMD_NAME }}.zip","version": "${{ github.ref_name }}"}' > ${{ env.ITEM_CMD_NAME }}/.info
        zip -r ${{ env.ITEM_CMD_NAME }} ${{ env.ITEM_CMD_NAME }}

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          ${{ env.MAIN_CMD_NAME }}.zip
          ${{ env.ITEM_CMD_NAME }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
